Apps_Django/Pedidos_Materiales/src_pedidos/app_procesos/urls.py
#Importaciones necesarias para el archivo.
from django.contrib import admin
from django.urls import path
from app_procesos.views import IndexUsuario, PedidoCreate, PedidoList, PedidoDelete, PedidoSearch, PedidoUpdate,MaterialDelete,MaterialList,AgregarMaterial,PedidoListAcademico,PedidoSearchAcademico,PedidoUpdateAcademico,PedidoRechazoAcademico,PedidoListMisional,PedidoSearchMisional,PedidoUpdateMisional,PedidoRechazoMisional,ArticuloCreate,ArticuloUpdate,PedidoListSubdirector,PedidoSearchSubdirector,PedidoUpdateSubdirector,PedidoRechazoSubdirector,PedidoListAlmacenista,PedidoSearchAlmacenista,VerificarExistencias,LlegoPedido,ReportePedidoPDF
from django.contrib.auth.decorators import login_required

urlpatterns = [
    ############################# URLS PARTICULARES ##############################
    path('index/', login_required(IndexUsuario), name='index'),
    path('listar_materiales/', login_required(MaterialList.as_view()), name='listar_materiales'),
    ######################### URLS PARA GESTOR DE AREA ###########################
    path('crear_articulo_gestor/', login_required(ArticuloCreate.as_view()), name='crear_articulo_gestor'),
    path('actualizar_articulo_gestor/<str:pk>', login_required(ArticuloUpdate.as_view()), name='actualizar_articulo_gestor'),
    ########################### URLS PARA INSTRUCTOR #############################
    path('crear_pedido/', login_required(PedidoCreate.as_view()), name='crear_pedido'),
    path('buscar_pedido/<int:pk>/', login_required(PedidoSearch), name='buscar_pedido'),
    path('listar_pedido/', login_required(PedidoList), name='listar_pedido'),
    path('eliminar_pedido/<int:pk>/', login_required(PedidoDelete.as_view()), name='eliminar_pedido'),
    path('enviar_pedido/<int:pk>/', login_required(PedidoUpdate.as_view()), name='enviar_pedido'),
    path('eliminar_material/<int:pk>/<int:pk_alt>', login_required(MaterialDelete.as_view()), name='eliminar_material'),
    path('agregar_material/<int:pk>/', login_required(AgregarMaterial.as_view()), name='agregar_material'),
    ####################### URLS PARA COORDINADOR ACADEMICO ######################
    path('listar_pedido_academico/', login_required(PedidoListAcademico), name='listar_pedido_academico'),
    path('buscar_pedido_academico/<int:pk>/', login_required(PedidoSearchAcademico), name='buscar_pedido_academico'),
    path('aceptar_pedido_academico/<int:pk>/', login_required(PedidoUpdateAcademico.as_view()), name='aceptar_pedido_academico'),
    path('rechazar_pedido_academico/<int:pk>/', login_required(PedidoRechazoAcademico.as_view()), name='rechazar_pedido_academico'),
    ####################### URLS PARA COORDINADOR MISIONAL ######################
    path('listar_pedido_misional/', login_required(PedidoListMisional), name='listar_pedido_misional'),
    path('buscar_pedido_misional/<int:pk>/', login_required(PedidoSearchMisional), name='buscar_pedido_misional'),
    path('aceptar_pedido_misional/<int:pk>/', login_required(PedidoUpdateMisional.as_view()), name='aceptar_pedido_misional'),
    path('rechazar_pedido_misional/<int:pk>/', login_required(PedidoRechazoMisional.as_view()), name='rechazar_pedido_misional'),
    ########################## URLS PARA SUB DIRECTOR ##########################
    path('listar_pedido_subdirector/', login_required(PedidoListSubdirector), name='listar_pedido_subdirector'),
    path('buscar_pedido_subdirector/<int:pk>/', login_required(PedidoSearchSubdirector), name='buscar_pedido_subdirector'),
    path('aceptar_pedido_subdirector/<int:pk>/', login_required(PedidoUpdateSubdirector.as_view()), name='aceptar_pedido_subdirector'),
    path('rechazar_pedido_subdirector/<int:pk>/', login_required(PedidoRechazoSubdirector.as_view()), name='rechazar_pedido_subdirector'),
    ########################### URLS PARA ALMACENISTA ##########################
    path('listar_pedido_almacenista/', login_required(PedidoListAlmacenista), name='listar_pedido_almacenista'),
    path('buscar_pedido_almacenista/<int:pk>/', login_required(PedidoSearchAlmacenista), name='buscar_pedido_almacenista'),
    path('verificar_existencias/<int:pk>/', login_required(VerificarExistencias.as_view()), name='verificar_existencias'),
    path('llego_pedido/<int:pk>/', login_required(LlegoPedido.as_view()), name='llego_pedido'),
    ############################### URLS PARA PDF ##############################
    path('reporte_pedido_pdf/<int:pk>/<int:pk_alt>/', login_required(ReportePedidoPDF.as_view()), name = 'reporte_pedido_pdf'),
]

Apps_Django/Pedidos_Materiales/src_pedidos/pedidos/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout_then_login
urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('inicio/', include(('app_procesos.urls', 'inicio'), namespace='inicio')),
    path('', auth_views.LoginView.as_view(template_name='index.html'), name='login'),
    path('logout/', logout_then_login, name= 'logout'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='index.html'), name='login'),
    path('reset/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/aceptar_pedido.html
{% extends "base/base.html" %}

{% block content %}
<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Aceptar pedido</span>
    </h1>
</div>
  <div class="container">
   <div class="container px-2 b-2">
      <div class="alert alert-primary" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Importante!</strong> Para aceptar el pedido solo oprima el boton aceptar pedido.
      </div>
    </div>
    <form method="POST">{% csrf_token %}
        <h5>Realmente quiere aceptar el pedido?</h5>
        <p>Si realmente quiere aceptar el pedido solo oprima el boton que dice aceptar pedido, una vez aceptar no tendra vuelta atras.</p>
        <div class="form-group">
          <input type="hidden" name="fecha_novedad" value="{% now "d/m/Y" %}">
        </div>
        <div class="form-group">
          <input type="hidden" name="responsable_r" value="{{object.responsable_r_id}}" >
        </div>
         <div class="form-group" >
            <input type="hidden" name="estado_r" value="{{'Enviado'}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="area_pedido_r" value="{{user.area_r_id}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="rol_pedido_r" value="{{"4"}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="nota_pedido" value="{{"N/A"}}">
        </div>
        <a class="btn btn-primary" href="{% url 'inicio:buscar_pedido_academico' object.checkpoint %}">Cancelar</a>
        <button type="submit" class="btn btn-success">Aceptar pedido</button>
    </form>
</div>
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/aceptar_pedido_misional.html
{% extends "base/base.html" %}

{% block content %}
<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Aceptar pedido</span>
    </h1>
</div>
  <div class="container">
   <div class="container px-2 b-2">
      <div class="alert alert-primary" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Importante!</strong> Para aceptar el pedido solo oprima el boton aceptar pedido.
      </div>
    </div>
    <form method="POST">{% csrf_token %}
        <h5>Realmente quiere aceptar el pedido?</h5>
        <p>Si realmente quiere aceptar el pedido solo oprima el boton que dice aceptar pedido, una vez aceptar no tendra vuelta atras.</p>
        <div class="form-group">
          <input type="hidden" name="fecha_novedad" value="{% now "d/m/Y" %}">
        </div>
        <div class="form-group">
          <input type="hidden" name="responsable_r" value="{{object.responsable_r_id}}" >
        </div>
         <div class="form-group" >
            <input type="hidden" name="estado_r" value="{{'Enviado'}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="area_pedido_r" value="{{object.area_pedido_r_id}}" >
        </div>
        <div class="form-group">
          <input type="hidden" name="rol_pedido_r" value="{{"5"}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="nota_pedido" value="{{"N/A"}}">
        </div>
        <a class="btn btn-primary" href="{% url 'inicio:buscar_pedido_misional' object.checkpoint %}">Cancelar</a>
        <button type="submit" class="btn btn-success">Aceptar pedido</button>
    </form>
</div>
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/aceptar_pedido_subdirector.html
{% extends "base/base.html" %}

{% block content %}
<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Aceptar pedido</span>
    </h1>
</div>
  <div class="container">
   <div class="container px-2 b-2">
      <div class="alert alert-primary" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Importante!</strong> Para aceptar el pedido solo oprima el boton aceptar pedido.
      </div>
    </div>
    <form method="POST">{% csrf_token %}
        <h5>Realmente quiere aceptar el pedido?</h5>
        <p>Si realmente quiere aceptar el pedido solo oprima el boton que dice aceptar pedido, una vez aceptar no tendra vuelta atras.</p>
        <div class="form-group">
          <input type="hidden" name="fecha_novedad" value="{% now "d/m/Y" %}">
        </div>
        <div class="form-group">
          <input type="hidden" name="responsable_r" value="{{object.responsable_r_id}}" >
        </div>
         <div class="form-group" >
            <input type="hidden" name="estado_r" value="{{'Enviado'}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="area_pedido_r" value="{{object.area_pedido_r_id}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="rol_pedido_r" value="{{"6"}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="nota_pedido" value="{{"N/A"}}">
        </div>
        <a class="btn btn-primary" href="{% url 'inicio:buscar_pedido_subdirector' object.checkpoint %}">Cancelar</a>
        <button type="submit" class="btn btn-success">Aceptar pedido</button>
    </form>
</div>
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/agregar_material.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/listas.css' %}">
<br>
<div class="text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Lista para agregar materiales al pedido</span>
    </h1>
</div>

<div class="container">
   <div class="container px-2 b-2">
      <div class="alert alert-primary" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Importante!</strong> Cuando quiera agregar un material solo indique la cantidad y oprima al botón agregar.
      </div>
</div>

<div class="wrapper">
    <div class="pull-right">
        <form method="GET">
        <input type="text" name="nombre_articulo__icontains" placeholder="Nombre producto" id="id_nombre_articulo__icontains">
        <button type="submit" class="btn btn-primary">Buscar</button>
        </form>
    </div>
    <div class="table">
        <div class="row header">
            <div class="cell">
                Codigo articulo
            </div>
            <div class="cell">
                Nombre articulo
            </div>
            <div class="cell">
                Fabricante
            </div>
            <div class="cell">
                Ficha tecnica
            </div>
            <div class="cell">
                Unidad metrica
            </div>
            <div class="cell">
                Lote
            </div>
            <div class="cell">
                Tipo de elemento
            </div>
            <div class="cell">
                Cantidad
            </div>
        </div>
        {% if filter %}
            {% for material in filter.qs %}
                <div class="row">
                    <div class="cell" data-title="Codigo articulo">
                        {{material.codigo_articulo}}
                    </div>
                    <div class="cell" data-title="Nombre articulo">
                        {{material.nombre_articulo}}
                    </div>
                    <div class="cell" data-title="Fabricante">
                        {{material.fabricante}}
                    </div>
                    <div class="cell" data-title="Ficha Tecnica">
                        {{material.ficha_tecnica}}
                    </div>
                    <div class="cell" data-title="Unidad metrica">
                        {{material.unidad_metrica_r}}
                    </div>
                    <div class="cell" data-title="Lote">
                        {{material.lote_articulo_r}}
                    </div>
                    <div class="cell" data-title="Tipo de elemento">
                        {{material.tipo_elemento_r}}
                    </div>


                    <form method="POST">{% csrf_token %}
                        <div class="cell" data-title="Cantidad">
                            <input type="number" min="1" style="width:50px;height:30px" name="cantidad_requerida" value="{{1}}">
                        </div>
                        <input type="hidden" name="fecha_pedido" value="{% now "d/m/Y" %}" >
                        <input type="hidden" name="responsable_r" value="{{user.id}}" >
                        <input type="hidden" name="codigo_articulo_r" value="{{material.codigo_articulo}}" >
                        {% for pedido in pedidos %}
                            <input type="hidden" name="pedido_guia_r" value="{{pedido.checkpoint}}" >
                            <div class="cell" data-title="Agregar al pedido">
                            <button type="submit" class="btn btn-success">Agregar</button>
                        {% endfor %}
                        </div>
                    </form>    
                </div>
            {% endfor %}
        {% else %}
            <h2 class="text-white">No hay materiales agregados</h2>
        {% endif %}
    </div>
</div>
    {% for pedido in pedidos %}
        <a class="btn btn-primary" href="{% url 'inicio:buscar_pedido' pedido.checkpoint%}">Regresar</a>
    {% endfor %}
{% endblock %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/eliminar_material.html
{% extends "base/base.html" %}
{% block content %}

<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
        <span class="text-dark">Eliminar articulo</span>
    </h1>
</div>
<div class="container px-2 b-2">
    <div class="alert alert-primary" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Importante!</strong> Para eliminar el material solo oprima el botón eliminar articulo.
    </div>
</div>
<div class="container">
    <form method="POST"> {% csrf_token %}
        {% for pedido in pedidos %}
            <h5>Desea eliminar el articulo {{ pedido.codigo_articulo_r.nombre_articulo }}?</h5>
            <p>Si realmente quiere eliminar el articulo solo oprima el botón que dice eliminar articulo.</p>
        {% endfor %}
        {% for guia in guias %}
            <a class="btn btn-primary" href="{% url 'inicio:buscar_pedido' guia.checkpoint %}">Cancelar</a>
        {% endfor %}    
            <button type="submit" class="btn btn-danger">Eliminar articulo</button>
    </form>
</div>
    
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/eliminar_pedido.html
{% extends "base/base.html" %}
{% block content %}
<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
        <span class="text-dark">Eliminar pedido</span>
    </h1>
</div>
<div class="container">
    <div class="container px-2 b-2">
        <div class="alert alert-primary" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>¡Importante!</strong> Para eliminar el pedido solo oprima el botón eliminar pedido.
        </div>
    </div>
    <form method="POST"> {% csrf_token %}
        <h5>Desea eliminar el pedido de {{ object.responsable_r }}?</h5>
        <p>Si realmente quiere eliminar el pedido solo oprima el botón que dice eliminar pedido.</p>
        <a class="btn btn-success" href="{% url 'inicio:listar_pedido' %}">Cancelar</a>
        <button type="submit" class="btn btn-danger">Eliminar pedido</button>
  </form>
</div>
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/enviar_pedido.html
{% extends "base/base.html" %}

{% block content %}
<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
        <span class="text-dark">Envio de pedido</span>
    </h1>
</div>
<div class="container">
    <div class="container px-2 b-2">
        <div class="alert alert-primary" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>¡Importante!</strong> Para enviar el pedido solo oprima el boton enviar pedido.
        </div>
    </div>
    <form method="POST">{% csrf_token %}
        <h5>Realmente quiere enviar el pedido?</h5>
        <p>Si realmente quiere enviar el pedido solo oprima el boton que dice enviar pedido, una vez enviado no tendra vuelta atras.</p>
        <div class="form-group">
            <input type="hidden" name="fecha_novedad" value="{% now "d/m/Y" %}">
        </div>
        <div class="form-group">
            <input type="hidden" name="responsable_r" value="{{user.id}}" >
        </div>
         <div class="form-group" >
            <input type="hidden" name="estado_r" value="{{'Enviado'}}" >
        </div>
        <div class="form-group">
            <input type="hidden" name="area_pedido_r" value="{{user.area_r_id}}" >
        </div>
        <div class="form-group">
            <input type="hidden" name="rol_pedido_r" value="{{"3"}}">
        </div>
        <div class="form-group">
            <input type="hidden" name="nota_pedido" value="{{"N/A"}}">
        </div>
        <a class="btn btn-primary" href="{% url 'inicio:buscar_pedido' object.checkpoint %}">Cancelar</a>
        <button type="submit" class="btn btn-success">Enviar pedido</button>
    </form>
</div>
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/llego_pedido.html
{% extends "base/base.html" %}

{% block content %}
<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Entregar pedido</span>
    </h1>
</div>
  <div class="container">
   <div class="container px-2 b-2">
      <div class="alert alert-primary" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Importante!</strong> Para cambiar el estado del pedido a entregando solo oprima el boton entregando pedido.
      </div>
    </div>
    <form method="POST">{% csrf_token %}
        <h5>Realmente quiere entregar el pedido?</h5>
        <p>Si realmente quiere entregar el pedido solo oprima el boton que dice entregar pedido.</p>
        <div class="form-group">
          <input type="hidden" name="fecha_novedad" value="{% now "d/m/Y" %}">
        </div>
        <div class="form-group">
          <input type="hidden" name="responsable_r" value="{{object.responsable_r_id}}" >
        </div>
         <div class="form-group" >
            <input type="hidden" name="estado_r" value="{{'Entregando'}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="area_pedido_r" value="{{object.area_pedido_r_id}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="rol_pedido_r" value="{{"6"}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="nota_pedido" value="{{"N/A"}}">
        </div>
        <a class="btn btn-primary" href="{% url 'inicio:buscar_pedido_almacenista' object.checkpoint %}">Cancelar</a>
        <button type="submit" class="btn btn-success">Entregando pedido</button>
    </form>
</div>
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/nuevo_articulo_gestor.html
{% extends "base/base.html" %}

{% block content %}
<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Creación o actualización de un articulo</span>
    </h1>
</div>
  <div class="container">
   <div class="container px-2 b-2">
      <div class="alert alert-primary" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Importante!</strong> Para crear o actualizar el articulo solo oprima el boton guardar articulo.
      </div>
    </div>
    <form method="POST">{% csrf_token %}
        <h5>Realmente quiere crear o actualizar el articulo?</h5>
        <p>Si realmente lo quiere hacer solo oprima el boton que dice guardar articulo.</p>
        <div class="form-group">
            <label for="{{form.codigo_articulo.name}}">{{form.codigo_articulo.label}}</label>
            {{form.codigo_articulo}}
        </div>
        <div class="form-group">
            <label for="{{form.nombre_articulo.name}}">{{form.nombre_articulo.label}}</label>
            {{form.nombre_articulo}}
        </div>
        <div class="form-group" >
            <label for="{{form.fabricante.name}}">{{form.fabricante.label}}</label>
            {{form.fabricante}}
        </div>
        <div class="form-group">
            <label for="{{form.ficha_tecnica.name}}">{{form.ficha_tecnica.label}}</label>
            {{form.ficha_tecnica}}
        </div>
        <div class="form-group">
        
            <label for="{{form.valor.name}}">{{form.valor.label}}</label>
            {{form.valor}}
        </div>
        <div class="form-group">
            <label for="{{form.unidad_metrica_r.name}}">{{form.unidad_metrica_r.label}}</label>
            {{form.unidad_metrica_r}}
        </div>
        <div class="form-group">
            <label for="{{form.lote_articulo_r.name}}">{{form.lote_articulo_r.label}}</label>
            {{form.lote_articulo_r}}
        </div>
        <div class="form-group">
            <label for="{{form.tipo_elemento_r.name}}">{{form.tipo_elemento_r.label}}</label>
            {{form.tipo_elemento_r}}
        </div>
        <a class="btn btn-primary" href="{% url 'inicio:index' %}">Regresar</a>
        <button type="submit" class="btn btn-success">Guardar articulo</button>
    </form>
    </div>
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/nuevo_pedido.html
{% extends "base/base.html" %}

{% block content %}
<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Creación de nuevo pedido</span>
    </h1>
</div>
  <div class="container">
   <div class="container px-2 b-2">
      <div class="alert alert-primary" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Importante!</strong> Para crear el pedido solo oprima el botón crear pedido.
      </div>
    </div>
    <form method="POST">{% csrf_token %}
        <h5>Realmente quiere crear el pedido?</h5>
        <p>Si realmente quiere crear el pedido solo oprima el botón que dice crear pedido.</p>
        <div class="form-group">
          <input type="hidden" name="fecha_novedad" value="{% now "d/m/Y" %}">
        </div>
        <div class="form-group">
          <input type="hidden" name="responsable_r" value="{{user.id}}" >
        </div>
         <div class="form-group" >
            <input type="hidden" name="estado_r" value="{{'Borrador'}}" >
        </div>
        <div class="form-group">
          <input type="hidden" name="area_pedido_r" value="{{user.area_r_id}}" >
        </div>
        <div class="form-group">
          <input type="hidden" name="rol_pedido_r" value="{{user.roll_r_id}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="nota_pedido" value="{{"N/A"}}">
        </div>
        <a class="btn btn-primary" href="{% url 'inicio:index' %}">Regresar</a>
        <button type="submit" class="btn btn-success">Crear pedido</button>
    </form>
    </div>
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/forms/rechazar_pedido.html
{% extends "base/base.html" %}

{% block content %}
<br>
<div class="row justify-content-center text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Rechazar pedido</span>
    </h1>
</div>
  <div class="container">
   <div class="container px-2 b-2">
      <div class="alert alert-primary" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>¡Importante!</strong> Para rechazar el pedido solo oprima el boton rechazar pedido.
      </div>
    </div>
    <form method="POST">{% csrf_token %}
        <h5>Realmente quiere rechazar el pedido?</h5>
        <p>Si realmente quiere rechazar el pedido solo oprima el boton que dice rechazar pedido, una vez rechazar no tendra vuelta atras.</p>
        <div class="form-group">
          <input type="hidden" name="fecha_novedad" value="{% now "d/m/Y" %}">
        </div>
        <div class="form-group">
          <input type="hidden" name="responsable_r" value="{{object.responsable_r_id}}" >
        </div>
         <div class="form-group" >
            <input type="hidden" name="estado_r" value="{{'Rechazado'}}">
        </div>
        <div class="form-group">
          <input type="hidden" name="area_pedido_r" value="{{object.area_pedido_r_id}}" >
        </div>
        <div class="form-group">
          <input type="hidden" name="rol_pedido_r" value="{{"1"}}">
        </div>
        <div class="form-group">
          <p>Nota pedido:</p>
          {{form.nota_pedido}}
        </div>
        <a class="btn btn-primary" href="{% url 'inicio:buscar_pedido_academico' object.checkpoint %}">Cancelar</a>
        <button type="submit" class="btn btn-danger">Rechazar pedido</button>
    </form>
</div>
{% endblock content %}