Apps_Django/Veterinaria/src/apps/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.mascota.views import listado,MascotaList,MascotaCreate, MascotaUpdate, MascotaDelete, ReporteMascotPDF
#from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete
urlpatterns = [
    url(r'^listar', login_required(MascotaList.as_view()), name = 'mascota_listar'),
    url(r'^nuevo$', login_required(MascotaCreate.as_view()), name = 'mascota_crear'),
    url(r'^editar/(?P<pk>[\w]+)$', login_required(MascotaUpdate.as_view()), name = 'mascota_editar'),
    url(r'^eliminar/(?P<pk>[\w]+)$', login_required(MascotaDelete.as_view()), name = 'mascota_eliminar'),
    url(r'^listado', listado, name = 'listado'),
    url(r'^reporte_mascota_pdf', login_required(ReporteMascotPDF.as_view()), name = 'reporte_mascota_pdf'),
]
"""
urlpatterns = [
    url(r'^$', index, name= 'index'),
    url(r'^nuevo$', mascota_view, name = 'mascota_crear'),
    url(r'^listar$', mascota_list, name = 'mascota_listar'),
    url(r'^editar/(?P<folio>[\w]+)$', mascota_edit, name = 'mascota_editar'),
    url(r'^eliminar/(?P<folio>[\w]+)$', mascota_delete, name = 'mascota_eliminar'),
]
"""

Apps_Django/Veterinaria/src/probar/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace= 'mascota')),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace= 'adopcion')),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace= 'usuarios')),
    url(r'^$', login, {'template_name':'index.html'}, name= 'login'),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name= 'login'),
    url(r'^logout/', logout_then_login, name= 'logout'),
    url(r'^reset/password_reset', password_reset,{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'}, name= 'password_reset'),
    url(r'^reset_password_done', password_reset_done,{'template_name':'registration/password_reset_done.html'}, name= 'password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,{'template_name':'registration/password_reset_confirm.html'}, name= 'password_reset_confirm'),
    url(r'^reset/done', password_reset_complete,{'template_name':'registration/password_reset_complete.html'}, name= 'password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Apps_Django/Veterinaria/src/apps/mascota/models.py
from django.db import models
from django.utils.translation import ugettext as _
from apps.adopcion.models import Persona


class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre)

class Mascota(models.Model):
    folio = models.CharField(max_length=10, primary_key=True)
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna)



    def __str__(self):
        return '{}'.format(self.folio)
    class Meta:
        permissions = {
            ('is_uno', _('Usuario Uno')),
            ('is_dos', _('Usuario Dos')),
        }

Apps_Django/Veterinaria/src/apps/mascota/forms.py
from django import forms
from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota

        fields = [
            'folio',
            'nombre',
            'sexo',
            'edad_aproximada',
            'fecha_rescate',
            'persona',
            'vacuna',

        ]

        labels= {
            'folio':'Folio',
            'nombre':'Nombre',
            'sexo' :'Sexo',
            'edad_aproximada' :'Edad Aproximada',
            'fecha_rescate' :'Fecha de Rescate',
            'persona':'Adoptante',
            'vacuna':'Vacuna',

        }

        widgets = {
            'folio': forms.TextInput(attrs={'class':'form-control'}),
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.TextInput(attrs={'class':'form-control'}),
            'edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
            'persona': forms.Select(attrs={'class':'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),

        }

Apps_Django/Veterinaria/src/apps/mascota/views.py
from django.shortcuts import render ,redirect
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota
from django.conf import settings
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle
from reportlab.lib.units import cm
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from django.views.generic import View

def listado(request):
    lista = serializers.serialize('json', Mascota.objects.all(), fields=['nombre','sexo'])
    return HttpResponse(lista, content_type='application/json')

class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'
    paginate_by = 5

class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')
    @method_decorator(permission_required('mascota.add_mascota', reverse_lazy('mascota:mascota_listar')))
    def dispatch(self, *args, **kwargs):
        return super(MascotaCreate, self).dispatch(*args, **kwargs)

class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')

    @method_decorator(permission_required('mascota.add_mascota', reverse_lazy('mascota:mascota_listar')))
    def dispatch(self, *args, **kwargs):
        return super(MascotaUpdate, self).dispatch(*args, **kwargs)

class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')
    @method_decorator(permission_required('mascota.add_mascota', reverse_lazy('mascota:mascota_listar')))
    def dispatch(self, *args, **kwargs):
        return super(MascotaDelete, self).dispatch(*args, **kwargs)

class ReporteMascotPDF(View):
    def cabecera(self, pdf):
        archivo_imagen = settings.STATIC_ROOT+'/img/logoSena.png'
        pdf.drawImage(archivo_imagen, 35, 750, 100, 90, preserveAspectRatio=True)
        pdf.setFont('Helvetica', 16)
        pdf.drawString(230, 790, u"SENA MAS TRABAJO")
        pdf.setFont('Helvetica', 14)
        pdf.drawString(235, 770, u"REPORTE MASCOTAS")


    def tabla(self,pdf,y):
        encabezado = ('Folio', 'Nombre', 'Sexo', 'Fecha rescate')
        detalle = [(mascota.folio, mascota.nombre, mascota.sexo, mascota.fecha_rescate) for mascota in Mascota.objects.all()]
        detalle_orden = Table([encabezado]+ detalle, colWidths = [2* cm, 5 * cm, 5 * cm, 5 * cm])
        detalle_orden.setStyle(TableStyle(
        [
            ('ALING', (0,0), (3,0), 'CENTER'),
            ('GRID', (0,0), (-1,-1), 1, colors.black),
            ('FONTSIZE', (0,0),(-1,-1),10),
        ]
        ))
        detalle_orden.wrapOn(pdf, 800, 600)
        detalle_orden.drawOn(pdf, 60, y)

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type= 'application/pdf')
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer)
        self.cabecera(pdf)
        y = 600
        self.tabla(pdf,y)
        pdf.showPage()
        pdf.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response


"""
def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota_listar')

    else:
        form =MascotaForm()
    return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_list(request):
    mascota = Mascota.objects.all().order_by('folio')
    contexto = {'mascota': mascota}
    return render(request, 'mascota/mascota_list.html',contexto)

def mascota_edit(request,folio):
    mascota= Mascota.objects.get(folio = folio)
    if request.method == 'GET':
        form= MascotaForm(instance = mascota)
    else:
        form = MascotaForm(request.POST, instance = mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota_listar')
    return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_delete(request,folio):
    mascota= Mascota.objects.get(folio = folio)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota_list')
    return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})
"""

Apps_Django/Veterinaria/src/templates/mascota/mascota_delete.html
{% extends "base/base.html" %}
{% block content %}
  <form method="POST"> {% csrf_token %}
      <h3>Desea eliminar el registro de {{ object.persona.nombre }}?</h3>
      <button type="submit" class="btn btn-danger">Eliminar</button>
      <a class="btn btn-success" href="{% url 'mascota:mascota_listar'%}">Cancelar</a>
  </form>
{% endblock content %}

Apps_Django/Veterinaria/src/templates/mascota/mascota_form.html
{% extends "base/base.html" %}

{% block content %}
    <form method="POST">{% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success">Guardar</button>
    </form>
{% endblock content %}

Apps_Django/Veterinaria/src/templates/mascota/mascota_list.html
{% extends "base/base.html" %}

{% block content %}
<a class="btn btn-primary" href="{% url 'mascota:mascota_crear' %}">Crear nueva mascota</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope='col'>Folio</th>
                <th scope='col'>Nombre</th>
                <th scope='col'>Sexo</th>
                <th scope='col'>Edad</th>
                <th scope='col'>Fecha Rescate</th>
                <th scope='col'>Adoptante</th>
                <th scope='col'>Acciones</th>
            </tr>
       <thead>
       <tbody>
         {% if object_list %}
            {% for mascota in object_list %}
            <tr class="table-light">
                <th scope='row'>{{mascota.folio}}</th>
                <td>{{mascota.nombre}}</td>
                <td>{{mascota.sexo}}</td>
                <td>{{mascota.edad_aproximada}}</td>
                <td>{{mascota.fecha_rescate}}</td>
                <td>{{mascota.persona.nombre}}  {{mascota.persona.apellidos}}</td>
              <td>
                {% if perms.mascota.is_uno %}
                <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.folio %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.folio %}">Eliminar</a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
         {% else %}
            <h1>No hay mascotas registradas</h1>

       {% endif %}
       </tbody>
       </table>
       <ul class="pager">
         {% if page_obj.has_previous %}
            <a class="btn btn-success" href="?page={{page_obj.previous_page_number}}">Previo</a>
         {% endif %}
         {% if page_obj.has_next %}
            <a class="btn btn-success" href="?page={{page_obj.next_page_number}}">Siguiente</a>
         {% endif %}
       </ul>
       <a class="btn btn-info " href="{% url 'mascota:reporte_mascota_pdf' %}">Reporte pdf</a>
{% endblock content %}