Apps_Django/Veterinaria/src/apps/adopcion/urls.py
from django.conf.urls import url,include
from django.contrib.auth.decorators import login_required
from apps.adopcion.views import SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

urlpatterns = [
    url(r'^listar$', login_required(SolicitudList.as_view()), name = 'solicitud_listar'),
    url(r'^nueva$', login_required(SolicitudCreate.as_view()), name = 'solicitud_Crear'),
    url(r'^editar/(?P<pk>\d+)$', login_required(SolicitudUpdate.as_view()), name = 'solicitud_editar'),
    url(r'^eliminar/(?P<pk>\d+)$', login_required(SolicitudDelete.as_view()), name = 'solicitud_eliminar'),
]

Apps_Django/Veterinaria/src/probar/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace= 'mascota')),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace= 'adopcion')),
    url(r'^usuarios/', include('apps.usuarios.urls', namespace= 'usuarios')),
    url(r'^$', login, {'template_name':'index.html'}, name= 'login'),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name= 'login'),
    url(r'^logout/', logout_then_login, name= 'logout'),
    url(r'^reset/password_reset', password_reset,{'template_name':'registration/password_reset_form.html','email_template_name':'registration/password_reset_email.html'}, name= 'password_reset'),
    url(r'^reset_password_done', password_reset_done,{'template_name':'registration/password_reset_done.html'}, name= 'password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,{'template_name':'registration/password_reset_confirm.html'}, name= 'password_reset_confirm'),
    url(r'^reset/done', password_reset_complete,{'template_name':'registration/password_reset_complete.html'}, name= 'password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Apps_Django/Veterinaria/src/apps/adopcion/models.py
from django.db import models

class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    domicilio = models.TextField()

    def __str__(self):
        return '{}{}'.format(self.nombre, self.apellidos)
        
class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null = True, blank = True)
    numero_mascotas = models.IntegerField()
    razones = models.TextField()

Apps_Django/Veterinaria/src/apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.adopcion.models import Solicitud, Persona

from apps.adopcion.form import SolicitudForm, PersonaForm
from django.core.urlresolvers import reverse_lazy

class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'
    paginate_by = 5

class SolicitudCreate(CreateView):
    model = Solicitud
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')
    @method_decorator(permission_required('adopcion.add_adopcion', reverse_lazy('adopcion:solicitud_listar')))
    def dispatch(self, *args, **kwargs):
        return super(SolicitudCreate, self).dispatch(*args, **kwargs)

    def get_context_data(self, **Kwargs):
        context = super(SolicitudCreate, self).get_context_data(**Kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2']= self.second_form_class(self.request.GET)
        return context

    def post(self, request, *arg, **Kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit = False)
            solicitud.persona = form2.save()
            solicitud.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

class SolicitudUpdate(UpdateView):
    model = Solicitud
    second_model = Persona
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')
    @method_decorator(permission_required('adopcion.add_adopcion', reverse_lazy('adopcion:solicitud_listar')))
    def dispatch(self, *args, **kwargs):
        return super(SolicitudUpdate, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SolicitudUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        solicitud = self.model.objects.get(id = pk)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2']= self.second_form_class(instance=persona)
        context['id']= pk
        return context
    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_solicitud = kwargs['pk']
        solicitud = self.model.objects.get(id=id_solicitud)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        form = self.form_class(request.POST, instance=solicitud)
        form2 = self.second_form_class(request.POST, instance=persona)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

class SolicitudDelete(DeleteView):
    model = Solicitud
    template_name = 'adopcion/solicitud_delete.html'
    success_url = reverse_lazy('adopcion:solicitud_listar')
    @method_decorator(permission_required('adopcion.add_adopcion', reverse_lazy('adopcion:solicitud_listar')))
    def dispatch(self, *args, **kwargs):
        return super(SolicitudUpdate, self).dispatch(*args, **kwargs)

Apps_Django/Veterinaria/src/templates/adopcion/solicitud_delete.html
{% extends "base/base.html" %}
{% block content %}
<form method="POST"> {% csrf_token %}
      <h3>Desea eliminar la solicitud {{object.persona.nombre}} {{object.persona.apellido}}?</h3>
      <button type="submit" class="btn btn-danger">Si, Eliminar</button>
      <a class="btn btn-success" href="{% url 'adopcion:solicitud_listar' %}">Cancelar</a>
  </form>
{% endblock content %}

Apps_Django/Veterinaria/src/templates/adopcion/solicitud_form.html
{% extends "base/base.html" %}
{% block content %}

  <form method="POST">{% csrf_token %}
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
          <label for="{{form2.nombre.name}}">{{form2.nombre.label}}</label>
          {{form2.nombre}}
        </div>
        <div class="form-group">
          <label for="{{form2.apellidos.name}}">{{form2.apellidos.label}}</label>
          {{form2.apellidos}}
        </div>
        <div class="form-group">
          <label for="{{form2.edad.name}}">{{form2.edad.label}}</label>
          {{form2.edad}}
        </div>
        <div class="form-group">
          <label for="{{form2.email.name}}">{{form2.email.label}}</label>
          {{form2.email}}
        </div>
        <div class="form-group">
          <label for="{{form2.telefono.name}}">{{form2.telefono.label}}</label>
          {{form2.telefono}}
        </div>
        <div class="form-group">
          <label for="{{form2.domicilio.name}}">{{form2.domicilio.label}}</label>
          {{form2.domicilio}}
        </div>
        <div class="form-group">
          <label for="{{form.numero_mascotas.name}}">{{form.numero_mascotas.label}}</label>
          {{form.numero_mascotas}}
        </div>
        <div class="form-group">
          <label for="{{form.razones.name}}">{{form.razones.label}}</label>
          {{form.razones}}
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
      </div>
    </div>
  </form>
{% endblock content%}

Apps_Django/Veterinaria/src/templates/adopcion/solicitud_list.html
{% extends "base/base.html" %}

{% block content %}
<a class="btn btn-primary" href="{% url 'adopcion:solicitud_Crear'%}">Crear nueva solicitud</a>
  <table class="table table-hover">
    <div class="row">


    <thead>
      <tr>
        <th scope="col">No. Solicitud</th>
        <th scope="col">Adoptante</th>
        <th scope="col">No. Mascota</th>
        <th scope="col">Razones</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% if object_list %}
        {% for solicitud in object_list %}
        <tr>
          <td>{{solicitud.id}}</td>
          <td>{{solicitud.persona.nombre}} {{solicitud.persona.apellidos}}</td>
          <td>{{solicitud.numero_mascotas}}</td>
          <td>{{solicitud.razones}}</td>
          <td>
            {% if perms.mascota.is_uno %}
            <a class="btn btn-primary" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
            <a class="btn btn-danger" href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      {% else %}
        <h1>No hay registros en las solicitudes.</h1>
      {% endif %}
    </tbody>
  </table>
  <ul class="pager">
    {% if page_obj.has_previous %}
       <a class="btn btn-success" href="?page={{page_obj.previous_page_number}}">Previo</a>
    {% endif %}
    {% if page_obj.has_next %}
       <a class="btn btn-success" href="?page={{page_obj.next_page_number}}">Siguiente</a>
    {% endif %}
  </ul>
</div>
{% endblock content %}