Apps_Django/Pedidos_Materiales/src_pedidos/app_procesos/urls.py
#Importaciones necesarias para el archivo.
from django.contrib import admin
from django.urls import path
from app_procesos.views import IndexUsuario, PedidoCreate, PedidoList, PedidoDelete, PedidoSearch, PedidoUpdate,MaterialDelete,MaterialList,AgregarMaterial,PedidoListAcademico,PedidoSearchAcademico,PedidoUpdateAcademico,PedidoRechazoAcademico,PedidoListMisional,PedidoSearchMisional,PedidoUpdateMisional,PedidoRechazoMisional,ArticuloCreate,ArticuloUpdate,PedidoListSubdirector,PedidoSearchSubdirector,PedidoUpdateSubdirector,PedidoRechazoSubdirector,PedidoListAlmacenista,PedidoSearchAlmacenista,VerificarExistencias,LlegoPedido,ReportePedidoPDF
from django.contrib.auth.decorators import login_required

urlpatterns = [
    ############################# URLS PARTICULARES ##############################
    path('index/', login_required(IndexUsuario), name='index'),
    path('listar_materiales/', login_required(MaterialList.as_view()), name='listar_materiales'),
    ######################### URLS PARA GESTOR DE AREA ###########################
    path('crear_articulo_gestor/', login_required(ArticuloCreate.as_view()), name='crear_articulo_gestor'),
    path('actualizar_articulo_gestor/<str:pk>', login_required(ArticuloUpdate.as_view()), name='actualizar_articulo_gestor'),
    ########################### URLS PARA INSTRUCTOR #############################
    path('crear_pedido/', login_required(PedidoCreate.as_view()), name='crear_pedido'),
    path('buscar_pedido/<int:pk>/', login_required(PedidoSearch), name='buscar_pedido'),
    path('listar_pedido/', login_required(PedidoList), name='listar_pedido'),
    path('eliminar_pedido/<int:pk>/', login_required(PedidoDelete.as_view()), name='eliminar_pedido'),
    path('enviar_pedido/<int:pk>/', login_required(PedidoUpdate.as_view()), name='enviar_pedido'),
    path('eliminar_material/<int:pk>/<int:pk_alt>', login_required(MaterialDelete.as_view()), name='eliminar_material'),
    path('agregar_material/<int:pk>/', login_required(AgregarMaterial.as_view()), name='agregar_material'),
    ####################### URLS PARA COORDINADOR ACADEMICO ######################
    path('listar_pedido_academico/', login_required(PedidoListAcademico), name='listar_pedido_academico'),
    path('buscar_pedido_academico/<int:pk>/', login_required(PedidoSearchAcademico), name='buscar_pedido_academico'),
    path('aceptar_pedido_academico/<int:pk>/', login_required(PedidoUpdateAcademico.as_view()), name='aceptar_pedido_academico'),
    path('rechazar_pedido_academico/<int:pk>/', login_required(PedidoRechazoAcademico.as_view()), name='rechazar_pedido_academico'),
    ####################### URLS PARA COORDINADOR MISIONAL ######################
    path('listar_pedido_misional/', login_required(PedidoListMisional), name='listar_pedido_misional'),
    path('buscar_pedido_misional/<int:pk>/', login_required(PedidoSearchMisional), name='buscar_pedido_misional'),
    path('aceptar_pedido_misional/<int:pk>/', login_required(PedidoUpdateMisional.as_view()), name='aceptar_pedido_misional'),
    path('rechazar_pedido_misional/<int:pk>/', login_required(PedidoRechazoMisional.as_view()), name='rechazar_pedido_misional'),
    ########################## URLS PARA SUB DIRECTOR ##########################
    path('listar_pedido_subdirector/', login_required(PedidoListSubdirector), name='listar_pedido_subdirector'),
    path('buscar_pedido_subdirector/<int:pk>/', login_required(PedidoSearchSubdirector), name='buscar_pedido_subdirector'),
    path('aceptar_pedido_subdirector/<int:pk>/', login_required(PedidoUpdateSubdirector.as_view()), name='aceptar_pedido_subdirector'),
    path('rechazar_pedido_subdirector/<int:pk>/', login_required(PedidoRechazoSubdirector.as_view()), name='rechazar_pedido_subdirector'),
    ########################### URLS PARA ALMACENISTA ##########################
    path('listar_pedido_almacenista/', login_required(PedidoListAlmacenista), name='listar_pedido_almacenista'),
    path('buscar_pedido_almacenista/<int:pk>/', login_required(PedidoSearchAlmacenista), name='buscar_pedido_almacenista'),
    path('verificar_existencias/<int:pk>/', login_required(VerificarExistencias.as_view()), name='verificar_existencias'),
    path('llego_pedido/<int:pk>/', login_required(LlegoPedido.as_view()), name='llego_pedido'),
    ############################### URLS PARA PDF ##############################
    path('reporte_pedido_pdf/<int:pk>/<int:pk_alt>/', login_required(ReportePedidoPDF.as_view()), name = 'reporte_pedido_pdf'),
]

Apps_Django/Pedidos_Materiales/src_pedidos/pedidos/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout_then_login
urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('inicio/', include(('app_procesos.urls', 'inicio'), namespace='inicio')),
    path('', auth_views.LoginView.as_view(template_name='index.html'), name='login'),
    path('logout/', logout_then_login, name= 'logout'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='index.html'), name='login'),
    path('reset/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Apps_Django/Pedidos_Materiales/src_pedidos/templates/vistas/buscar_pedido.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/listas.css' %}">
<br>
<div class="text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Información del pedido</span>
    </h1>
</div>
<div class="container">
    {% if pedidos %}
        {% for pedido in pedidos %}
            <ul class="list-group">
                <li class="list-group-item active">Informacion completa del pedido</li>
                <li class="list-group-item">Fecha novedad del pedido: {{pedido.fecha_novedad}}</li>
                <li class="list-group-item">Responsable del pedido: {{pedido.responsable_r}}</li>
                <li class="list-group-item">Estado del pedido: {{pedido.estado_r}}</li>
                <li class="list-group-item">Area del pedido: {{pedido.area_pedido_r}}</li>
                <li class="list-group-item">Esta en revisión por: {{pedido.rol_pedido_r}}</li>
                <li class="list-group-item">Nota pedido: {{pedido.nota_pedido}}</li>
                {% if perms.app_usuarios.is_coordinador_misional %}
                    <li class="list-group-item">Precio pedido: {{precio}}</li>
                {% endif %}
            </ul>
            <br>
            {% if perms.app_usuarios.is_instructor %}
                {% if pedido.estado_r_id == "Borrador" %}
                    <a class="btn btn-primary" href="{% url 'inicio:listar_pedido'  %}">Regresar</a>
                    <a class="btn btn-info" href="{% url 'inicio:agregar_material' pedido.checkpoint %}">Agregar materiales</a>
                    <a class="btn btn-success" href="{% url 'inicio:enviar_pedido' pedido.checkpoint %}">Enviar pedido</a>
                {% endif %}
                {% if pedido.estado_r_id == "Rechazado" %}
                    <a class="btn btn-primary" href="{% url 'inicio:listar_pedido'  %}">Regresar</a>
                    <a class="btn btn-info" href="{% url 'inicio:agregar_material' pedido.checkpoint %}">Agregar materiales</a>
                    <a class="btn btn-success" href="{% url 'inicio:enviar_pedido' pedido.checkpoint %}">Enviar pedido</a>
                {% endif %}
                {% if pedido.estado_r_id == "Enviado" %}
                    <a class="btn btn-primary" href="{% url 'inicio:listar_pedido'  %}">Regresar</a>
                {% endif %}
            {% endif %}

            {% if perms.app_usuarios.is_cordinador_academico %}
                    <a class="btn btn-primary" href="{% url 'inicio:listar_pedido_academico'  %}">Regresar</a>
                    <a class="btn btn-success" href="{% url 'inicio:aceptar_pedido_academico' pedido.checkpoint %}">Aceptar pedido</a>
                    <a class="btn btn-danger" href="{% url 'inicio:rechazar_pedido_academico' pedido.checkpoint %}">Rechazar pedido</a>
            {% endif %}
            {% if perms.app_usuarios.is_coordinador_misional %}
                    <a class="btn btn-primary" href="{% url 'inicio:listar_pedido_misional'  %}">Regresar</a>
                    <a class="btn btn-success" href="{% url 'inicio:aceptar_pedido_misional' pedido.checkpoint %}">Aceptar pedido</a>
                    <a class="btn btn-danger" href="{% url 'inicio:rechazar_pedido_misional' pedido.checkpoint %}">Rechazar pedido</a>
            {% endif %}
            {% if perms.app_usuarios.is_subdirector %}
                    <a class="btn btn-primary" href="{% url 'inicio:listar_pedido_subdirector'  %}">Regresar</a>
                    <a class="btn btn-success" href="{% url 'inicio:aceptar_pedido_subdirector' pedido.checkpoint %}">Aceptar pedido</a>
                    <a class="btn btn-danger" href="{% url 'inicio:rechazar_pedido_subdirector' pedido.checkpoint %}">Rechazar pedido</a>
            {% endif %}
            {% if perms.app_usuarios.is_almacenista %}
                {% if pedido.estado_r_id == "Entregando" %}
                    <a class="btn btn-primary" href="{% url 'inicio:listar_pedido_almacenista'  %}">Regresar</a>
                    <a class="btn btn-info " href="{% url 'inicio:reporte_pedido_pdf' pedido.checkpoint pedido.area_pedido_r_id %}">Reporte PDF</a>
                {% else %}
                    <a class="btn btn-primary" href="{% url 'inicio:listar_pedido_almacenista'  %}">Regresar</a>
                    <a class="btn btn-success" href="{% url 'inicio:verificar_existencias' pedido.checkpoint %}">Verificar existencias</a>
                    <a class="btn btn-success" href="{% url 'inicio:llego_pedido' pedido.checkpoint %}">Llego pedido</a>
                    <a class="btn btn-info " href="{% url 'inicio:reporte_pedido_pdf' pedido.checkpoint pedido.area_pedido_r_id %}">Reporte PDF</a>
                {% endif %}



            {% endif %}
        {% endfor %}
    {% endif %}
</div>

<br>
<div class="text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Lista de materiales del pedido</span>
    </h1>
</div>

<div class="wrapper">
    <div class="table">
        <div class="row header">
            <div class="cell">
                Codigo articulo
            </div>
            <div class="cell">
                Fecha ultima modificación
            </div>
            <div class="cell">
                Cantidad requerida
            </div>
            <div class="cell">
                Existencias
            </div>
            {% for pedido in pedidos %}
                {% if pedido.estado_r_id == "Borrador" %}
                    <div class="cell">
                        Eliminar articulo
                    </div>
                {% endif %}
                {% if pedido.estado_r_id == "Rechazado" %}
                    <div class="cell">
                        Eliminar articulo
                    </div>

                {% endif %}
            {% endfor %}
           
        </div>
        {% if materiales %}
            {% for material in materiales %}
                <div class="row">
                    <div class="cell" data-title="Codigo producto">
                        {{material.codigo_articulo_r}}
                    </div>
                    <div class="cell" data-title="Ultima modificacion">
                        {{material.fecha_pedido}}
                    </div>
                    <div class="cell" data-title="Cantidad">
                        {{material.cantidad_requerida}}
                    </div>
                    <div class="cell" data-title="Existencias">
                        {{material.existencias}}
                    </div>
                    {% for pedido in pedidos %}
                        {% if pedido.estado_r_id == "Borrador" %}
                            <div class="cell" data-title="Eliminar material">
                                <td align="center"><a class="btn" href="{% url 'inicio:eliminar_material' material.codigo_pedido pedido.checkpoint %}"><em class="fa fa-2x fa-trash"></em></a></td>
                            </div>

                        {% endif %}
                        {% if pedido.estado_r_id == "Rechazado" %}
                            <div class="cell" data-title="Eliminar material">
                                <td align="center"><a class="btn" href="{% url 'inicio:eliminar_material' material.codigo_pedido pedido.checkpoint %}"><em class="fa fa-2x fa-trash"></em></a></td>
                            </div>
                        {% endif %}

                    {% endfor %}
                   
                </div>
            {% endfor %}
        {% else %}
            <h2 class="text-white">No hay materiales agregados</h2>
        {% endif %}
    </div>
</div>
<br>
{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/vistas/inicio.html
{% extends "base/base.html" %}
{% block content %}
<br>
<div class="overflow-auto">

<!--================== INICIO PARA EL INSTRUCTOR ==================-->
{% if perms.app_usuarios.is_instructor %}
<div class="container">
  <div class="row mb-4 justify-content-center text-center">
    <div class="mb-5">
      <h1 class="section-title-underline mb-5">
        <span class="text-dark">Bienvenido {{request.user.roll_r}}</span>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light" >
        <div class="icon-wrapper bg-success">
          <span class="fa fa-plus text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Crear pedido</h2>
          <p class="grayy">En esta opción podras crear un nuevo pedido de tu area asignada.</p>
          <p><a href="{% url 'inicio:crear_pedido' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light">
        <div class="icon-wrapper bg-success">
          <span class="fa fa-th-list text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Listar pedido</h2>
          <p class="grayy">En esta opción podras listar tus pedidos creados para eliminarlos o editarlos.</p>
          <p><a href="{% url 'inicio:listar_pedido' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light">
        <div class="icon-wrapper bg-success">
          <span class="fa fa-archive text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Listar productos</h2>
          <p class="grayy">Esta opción podras ver todos los productos que se podran pedir.</p>
          <p><a href="{% url 'inicio:listar_materiales' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
<!--================== INICIO PARA EL GESTOR DE AREA ==================-->
{% if perms.app_usuarios.is_gestor_de_area %}
<div class="container">
  <div class="row mb-4 justify-content-center text-center">
    <div class="col-lg-4 mb-5">
      <h1 class="section-title-underline mb-5">
        <span class="text-dark">Bienvenido {{request.user.roll_r}}</span>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light" >
        <div class="icon-wrapper bg-success">
          <span class="fa fa-plus text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Crear articulo</h2>
          <p class="grayy">En esta opción podras crear un nuevo articulo.</p>
          <p><a href="{% url 'inicio:crear_articulo_gestor' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light">
        <div class="icon-wrapper bg-success">
          <span class="fa fa-archive text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Listar productos</h2>
          <p class="grayy">Esta opción podras ver todos los productos.</p>
          <p><a href="{% url 'inicio:listar_materiales' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
<!--================== INICIO PARA EL COORDINADOR ACADEMICO ==================-->
{% if perms.app_usuarios.is_cordinador_academico %}
<div class="container">
  <div class="row mb-4 justify-content-center text-center">
    <div class="col-lg-4 mb-5">
      <h1 class="section-title-underline mb-5">
        <span class="text-dark">Bienvenido {{request.user.roll_r}}</span>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light" >
        <div class="icon-wrapper bg-success">
          <span class="fa fa-th-list text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Pedidos recibidos</h2>
          <p class="grayy">En esta opción podras ver los pedidos enviados por los instructores del area asignada.</p>
          <p><a href="{% url 'inicio:listar_pedido_academico' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light">
        <div class="icon-wrapper bg-success">
          <span class="fa fa-archive text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Listar productos</h2>
          <p class="grayy">Esta opción podras ver todos los productos que se podran pedir.</p>
          <p><a href="{% url 'inicio:listar_materiales' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
<!--================== INICIO PARA EL COORDINADOR MISIONAL ==================-->
{% if perms.app_usuarios.is_coordinador_misional %}
<div class="container">
  <div class="row mb-4 justify-content-center text-center">
    <div class="col-lg-4 mb-5">
      <h1 class="section-title-underline mb-5">
        <span class="text-dark">Bienvenido {{request.user.roll_r}}</span>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light" >
        <div class="icon-wrapper bg-success">
          <span class="fa fa-th-list text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Pedidos recibidos</h2>
          <p class="grayy">En esta opción podras ver los pedidos enviados por los coordinadores academicos.</p>
          <p><a href="{% url 'inicio:listar_pedido_misional' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light">
        <div class="icon-wrapper bg-success">
          <span class="fa fa-archive text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Listar productos</h2>
          <p class="grayy">Esta opción podras ver todos los productos que se podran pedir.</p>
          <p><a href="{% url 'inicio:listar_materiales' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% if perms.app_usuarios.is_subdirector %}
<div class="container">
  <div class="row mb-4 justify-content-center text-center">
    <div class="col-lg-4 mb-5">
      <h1 class="section-title-underline mb-5">
        <span class="text-dark">Bienvenido {{request.user.roll_r}}</span>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light" >
        <div class="icon-wrapper bg-success">
          <span class="fa fa-th-list text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Pedidos recibidos</h2>
          <p class="grayy">En esta opción podras ver los pedidos enviados por los coordinadores misionales.</p>
          <p><a href="{% url 'inicio:listar_pedido_subdirector' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light">
        <div class="icon-wrapper bg-success">
          <span class="fa fa-archive text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Listar productos</h2>
          <p class="grayy">Esta opción podras ver todos los productos que se podran pedir.</p>
          <p><a href="{% url 'inicio:listar_materiales' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% if perms.app_usuarios.is_almacenista %}
<div class="container">
  <div class="row mb-4 justify-content-center text-center">
    <div class="col-lg-4 mb-5">
      <h1 class="section-title-underline mb-5">
        <span class="text-dark">Bienvenido {{request.user.roll_r}}</span>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light" >
        <div class="icon-wrapper bg-success">
          <span class="fa fa-th-list text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Pedidos recibidos</h2>
          <p class="grayy">En esta opción podras ver los pedidos aceptados por el sub director.</p>
          <p><a href="{% url 'inicio:listar_pedido_almacenista' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
      <div class="feature-1 border bg-light">
        <div class="icon-wrapper bg-success">
          <span class="fa fa-archive text-white"></span>
        </div>
        <div class="feature-1-content">
          <h2>Listar productos</h2>
          <p class="grayy">Esta opción podras ver todos los productos que se podran pedir.</p>
          <p><a href="{% url 'inicio:listar_materiales' %}" class="btn btn-success px-4 rounded-0">Ver</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% if not perms.app_usuarios.is_instructor and not perms.app_usuarios.is_gestor_de_area and not perms.app_usuarios.is_cordinador_academico and not perms.app_usuarios.is_coordinador_misional and not perms.app_usuarios.is_subdirector and not perms.app_usuarios.is_almacenista and not perms.app_usuarios.is_administrador %}
  <h1 class="text-white">Usted no tiene ningun permiso asignado, porfavor contacte con el administrador acargo para que le asigne los permisos correspondientes</h1>
{% endif %}

{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/vistas/listar_pedido.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/listas.css' %}">
<br>
<div class="text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Lista de pedidos</span>
    </h1>
</div>

<div class="wrapper">
  <div class="table">
    <div class="row header">
      <div class="cell">
        Id
      </div>
      <div class="cell">
        Ultima modificacion
      </div>
      <div class="cell">
        Area
      </div>
      <div class="cell">
        Estado del pedido
      </div>
      <div class="cell">
        Nota del pedido
      </div>
      <div class="cell">
        Información pedido
      </div>
      <div class="cell">
        Eliminar pedido
      </div>
    </div>
    {% if pedidos %}
        {% for pedido in pedidos %}
          <div class="row">
            <div class="cell" data-title="Id">
                {{pedido.checkpoint}}
            </div>
            <div class="cell" data-title="Ultima modificacion">
                {{pedido.fecha_novedad}}
            </div>
            <div class="cell" data-title="Area">
                {{pedido.area_pedido_r}}
            </div>
            <div class="cell" data-title="Estado del pedido">
                {{pedido.estado_r_id}}
            </div>
            <div class="cell" data-title="Estado del pedido">
                {{pedido.nota_pedido}}
            </div>
            <div class="cell" data-title="Información pedido">
                <a class="btn" href="{% url 'inicio:buscar_pedido' pedido.checkpoint %}"><em class="fa fa-lg fa-search"></em></a>
            </div>
            <div class="cell" data-title="Eliminar pedido">
                {% if pedido.estado_r_id == "Borrador" %}
                    <td align="center"><a class="btn" href="{% url 'inicio:eliminar_pedido' pedido.checkpoint %}"><em class="fa fa-2x fa-trash"></em></a></td>
                {% endif %}
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h2 class="text-dark">No hay pedidos creados</h2>
      {% endif %}
</div>

<a class="btn btn-primary" href="{% url 'inicio:index' %}">Regresar</a>




{% endblock content %}

Apps_Django/Pedidos_Materiales/src_pedidos/templates/vistas/pedidos_academico.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/listas.css' %}">
<br>
<div class="text-center">
    <h1 class="section-title-underline mb-5">
      <span class="text-dark">Lista de pedidos</span>
    </h1>
</div>

<div class="wrapper">
  <div class="table">
    <div class="row header">
      <div class="cell">
        Id
      </div>
      <div class="cell">
        Ultima modificacion
      </div>
      <div class="cell">
        Area
      </div>
      <div class="cell">
        Estado del pedido
      </div>
      <div class="cell">
        Nota del pedido
      </div>
      <div class="cell">
        Responsable
      </div>
      <div class="cell">
        Información pedido
      </div>
    </div>
    {% if pedidos %}
        {% for pedido in pedidos %}
          <div class="row">
            <div class="cell" data-title="Id">
                {{pedido.checkpoint}}
            </div>
            <div class="cell" data-title="Ultima modificacion">
                {{pedido.fecha_novedad}}
            </div>
            <div class="cell" data-title="Area">
                {{pedido.area_pedido_r}}
            </div>
            <div class="cell" data-title="Estado del pedido">
                {{pedido.estado_r_id}}
            </div>
            <div class="cell" data-title="Estado del pedido">
                {{pedido.nota_pedido}}
            </div>
            <div class="cell" data-title="Estado del pedido">
                {{pedido.responsable_r}}
            </div>
            <div class="cell" data-title="Información pedido">
                <a class="btn" href="{% url 'inicio:buscar_pedido_academico' pedido.checkpoint %}"><em class="fa fa-lg fa-search"></em></a>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h2 class="text-dark">No hay pedidos por revisar</h2>
      {% endif %}
</div>
  
<a class="btn btn-primary" href="{% url 'inicio:index' %}">Regresar</a>


  

{% endblock content %}